version: 2.1

commands:
  setup-tooling:
    description: "Install tools and configure kubectl for sonarqube access"
    steps:
      - kubernetes/install
      - helm/install-helm-client:
          version: v2.13.1
      - run:
          name: Set up a kubectl context for tooling
          command: |
            echo -n "${KUBE_ENV_TOOLING_CACERT}" | base64 -d > /tmp/cluster_tooling_ca.crt
            kubectl config set-cluster "${KUBE_ENV_TOOLING_NAME}" \
              --certificate-authority="/tmp/cluster_tooling_ca.crt" \
              --server="https://api.${KUBE_ENV_TOOLING_NAME}"
            kubectl config set-credentials circleci_tooling \
              --token="${KUBE_ENV_TOOLING_TOKEN}"
            kubectl config set-context circleci_tooling \
              --cluster="${KUBE_ENV_TOOLING_NAME}" \
              --user="circleci" \
              --namespace="${KUBE_ENV_TOOLING_NAMESPACE}"
            # confirm setup is ok
            kubectl config use-context circleci_tooling
            kubectl -n "${KUBE_ENV_TOOLING_NAMESPACE}" get secret hmpps-pcs-tooling-sonarqube-user-token

executors:
  setup-tooling:
    docker:
      - image: circleci/python:3
  builder:
    docker:
      - image: gradle:jdk11
    working_directory: ~/app
  sonar-scanner:
    docker:
      - image: sonarsource/sonar-scanner-cli:4.2
        environment:
          SONAR_HOST_URL: https://pcs-sonarqube.apps.live-1.cloud-platform.service.justice.gov.uk/
          SONAR_PROJECT_KEY: digital-probation-java-skeleton:foo
    working_directory: ~/app

orbs:
  kubernetes: circleci/kubernetes@0.3.0
  helm: circleci/helm@0.1.2
  owasp: entur/owasp@0.0.10

jobs:
  setup-tooling:
    executor: setup-tooling
    steps:
      - setup-tooling

  build_and_test:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: gradle clean build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: service/build/reports
      - store_artifacts:
          path: service/build/reports
      - run: gradle jacocoTestReport jacocoTestCoverageVerification
      - persist_to_workspace:
          root: .
          paths:
            - service/build/reports
  sonar-scan:
    executor: sonar-scanner
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Run sonar scan
          command: |
            set -euo pipefail
            declare -a args
            add_env_var_as_env_prop() {
              if [ "$1" ]; then
                args+=("-D$2=$1")
              fi
            }
            add_env_var_as_env_prop "${SONAR_LOGIN:-}" "sonar.login"
            add_env_var_as_env_prop "${SONAR_PASSWORD:-}" "sonar.password"
            add_env_var_as_env_prop "${SONAR_USER_HOME:-}" "sonar.userHome"
            add_env_var_as_env_prop "${SONAR_PROJECT_BASE_DIR:-}" "sonar.projectBaseDir"
            add_env_var_as_env_prop "${SONAR_PROJECT_KEY:-}" "sonar.projectKey"
            PROJECT_BASE_DIR="$PWD"
            if [ "${SONAR_PROJECT_BASE_DIR:-}" ]; then
              PROJECT_BASE_DIR="${SONAR_PROJECT_BASE_DIR}"
            fi
            export SONAR_USER_HOME="$PROJECT_BASE_DIR/.sonar"
            sonar-scanner "${args[@]}"

workflows:
  version: 2
  code-quality:
    jobs:
      - build_and_test
      - owasp/gradle_owasp_dependency_check
      - sonar-scan:
          requires:
            - build_and_test
